CREATE TABLE tbCliente
(CPF VARCHAR(11),
NOME VARCHAR(100),
ENDERECO_1 VARCHAR(150),
ENDERECO_2 VARCHAR(150),
BAIRRO VARCHAR(50),
CIDADE VARCHAR(50),
ESTADO VARCHAR(50),
CEP VARCHAR(8),
IDADE SMALLINT,
SEXO VARCHAR(1),
LIMITE_CREDITO FLOAT,
VOLUME_COMPRA FLOAT,
PRIMEIRA_COMPRA BIT(1))

DROP TABLE TABELA_DE_VENDEDORES

CREATE TABLE TABELA_DE_VENDEDORES
(NOME VARCHAR(100),
MATRICULA VARCHAR(5),
PERCENTUAL_COMISSAO FLOAT)